//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Registration
    {
        public int RegId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyGST { get; set; }
        public string CompanyPan { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyContact { get; set; }
        public string CompanyAlternetNo { get; set; }
        public Nullable<int> RegType { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> RegStatus { get; set; }
    }
}
