//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetalInventoryEntities : DbContext
    {
        public MetalInventoryEntities()
            : base("name=MetalInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master_CommonType> Master_CommonType { get; set; }
        public virtual DbSet<Master_CommonValue> Master_CommonValue { get; set; }
        public virtual DbSet<Master_Registration> Master_Registration { get; set; }
        public virtual DbSet<Master_UserMaster> Master_UserMaster { get; set; }
        public virtual DbSet<Master_RoleMaster> Master_RoleMaster { get; set; }
        public virtual DbSet<Transaction_BankTransactions> Transaction_BankTransactions { get; set; }
        public virtual DbSet<Master_BankAccountMaster> Master_BankAccountMaster { get; set; }

        public System.Data.Entity.DbSet<InventoryRepository.Masters.BankAccMasterModel> BankAccMasterModels { get; set; }
    }
}
