//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_BankTransactions
    {
        public int TranId { get; set; }
        public Nullable<int> fromAccount { get; set; }
        public Nullable<decimal> amtIn { get; set; }
        public Nullable<decimal> amtOut { get; set; }
        public string FormName { get; set; }
        public Nullable<int> toAccount { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<int> freez { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> yearId { get; set; }
    }
}
